services:
  postgres:
    image: postgres:16
    container_name: agent_postgres
    restart: always
    environment:
      POSTGRES_USER: agent
      POSTGRES_PASSWORD: agentpass
      POSTGRES_DB: agentdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - agentnet

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    networks:
      - agentnet

  printguard:
    image: ghcr.io/oliverbravery/printguard:latest
    container_name: printguard
    privileged: true   # potřebné pro kamery
    ports:
      - "7999:8000"    # host 7999 → container 8000
    volumes:
      - ./data:/data   # persistentní úložiště
    environment:
      - SECRET_KEY=change_me_to_anything
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    networks:
      - agentnet

      #version: "3.9"


  #printer-ai:
  # build: .
  #  container_name: printer-ai
  #  restart: unless-stopped
  #  ports:
  #    - "8000:8000"
  #  volumes:
  #    - ./weights:/app/weights
  #    - ./data:/app/data
  #    - ./feedback:/app/feedback
  #  environment:
  #    # případně nějaké env proměnné, když budeš chtít
  #    # - LOG_LEVEL=info
  #    PYTHONUNBUFFERED: "1"



  error-listener:
    build: ./listener
    container_name: error_listener
    depends_on:
      - postgres
    networks:
      - agentnet
    environment:
      POSTGRES_DB: agentdb
      POSTGRES_USER: agent
      POSTGRES_PASSWORD: agentpass
      POSTGRES_HOST: postgres
      N8N_WEBHOOK_URL: http://n8n:5678/webhook-test/webhook/error-alert

  general:
    build: ./General
    container_name: general
    depends_on:
      - ollama
      - skladnik
      - nakupcik
    environment:
      OLLAMA_URL: http://ollama:11434
    ports:
      - "8000:8000"
    networks:
      - agentnet

  skladnik:
    build: ./Skladník
    container_name: skladnik
    ports:
      - "8001:8001"
    networks:
      - agentnet

  nakupcik:
    build: ./Nakupcik
    container_name: nakupcik
    ports:
      - "8002:8002"
    networks:
      - agentnet

  access-request-server:
    build: ./AccessRequest
    container_name: AccessRequestServer
    ports:
      - "8003:8003"
    networks:
      - agentnet
    environment:
      POSTGRES_DB: agentdb
      POSTGRES_USER: agent
      POSTGRES_PASSWORD: agentpass
      POSTGRES_HOST: postgres

  security-agent:
    build:  
      context: ./Security_agent
      dockerfile: Dockerfile
    container_name: security-agent
    ports:    
      - "8004:8004"
    depends_on:
      - postgres
      - ollama
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: agent
      POSTGRES_PASSWORD: agentpass
      POSTGRES_DB: agentdb
      OLLAMA_HOST: http://ollama:11434
    env_file:
      - ./SECURITY_AGENT/.env



  ui:
    build: ./UI
    container_name: ui
    depends_on:
      - general
    ports:
      - "5173:80"
    networks:
      - agentnet

networks:
  agentnet:

volumes:
  postgres_data:
  ollama-data:
